on:
  push:
  workflow_dispatch:
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, ubuntu-20.04]
    steps:
    - name: Run a command
      run: echo "Hello World!"
